### ISSUE TITLE
Add MAX_WORKERS to customer-simulator (scenario-player) deployment

### ISSUE THREAD

**Issue by karol-brejna-i** [karol-brejna-i/retailstoreofthefuture#19]
Now, by default, multiple gunicorn workers are created (see: [tiangolo/uvicorn-gunicorn-fastapi:python3.8](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/tree/master#max_workers). 
Most of the time, a single worker is enough. 
```
      env:
        - name: LOG_LEVEL
          value: info
        - name: MAX_WORKERS
          value: '1'
```

(
